# Generated by Django 4.2.4 on 2024-01-07 07:03

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='FECHA DE SERVICIO')),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('direccion', models.CharField(max_length=200, verbose_name='DIRECCION DEL CULTO DE ALTAR')),
                ('lectura', models.TextField(verbose_name='LECTURA DE LA PALABRAS')),
                ('devocional_1', models.CharField(max_length=100, verbose_name='DEVOCIONAL')),
                ('cultural', models.TextField(verbose_name='CULTURAL')),
                ('mensaje', models.TextField(verbose_name='MENSAJE DE LAS PALABRAS')),
                ('description', models.TextField(blank=True, null=True, verbose_name='DESCRIPCION')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOMBRE')),
                ('lastname', models.CharField(max_length=50, verbose_name='APELLIDOS')),
                ('dni', models.BigIntegerField(blank=True, null=True, unique=True, validators=[app.models.validate_dni_length], verbose_name='CEDULA')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15, verbose_name='GENERO')),
                ('date_joined', models.DateField(verbose_name='FECHA DE NACIMIENTO')),
                ('address', models.CharField(max_length=150, verbose_name='DIRECCION')),
                ('fecha_ingreso', models.DateField(verbose_name='FECHA DE INGRESO')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, validators=[app.models.validate_phone_prefix], verbose_name='TELEFONO')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='CORREO ELECTRONICO')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='IMAGEN')),
                ('category', models.CharField(choices=[('joven', 'Joven'), ('dama', 'Dama'), ('caballero', 'Caballero'), ('adolecente', 'Adolecente')], max_length=20, verbose_name='CATEGORIA')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo', verbose_name='CARGO')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='ESTADO')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'miembro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOMBRE DEL GRUPO')),
                ('members', models.ManyToManyField(related_name='grupos', to='app.miembro', verbose_name='MIEMBROS DEL GRUPO')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('present', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presente')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app.miembro', verbose_name='MIEMBRO')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
