# Generated by Django 4.2.4 on 2024-01-09 05:28

import app.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='service',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='FECHA DE SERVICIO'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='PRESENTE'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[app.models.validate_dni_length, django.core.validators.MaxLengthValidator(limit_value=11, message='El DNI debe tener 11 dígitos.')], verbose_name='TELEFONO'),
        ),
    ]
