# Generated by Django 5.0.2 on 2024-03-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enfermo', 'Miembro se encuentra enfermo'), ('visitar', 'Miembro necesita ser visitado'), ('permiso', 'Miembro tiene permiso o excusa')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro')),
            ],
        ),
    ]
