# Generated by Django 4.2 on 2023-08-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_asistencia_hora_asistencia_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
