# Generated by Django 5.0.3 on 2024-05-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_miembro_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='phone',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, verbose_name='TELEFONO'),
        ),
    ]
