# Generated by Django 5.0.2 on 2024-03-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_miembrostatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembrostatus',
            options={'ordering': ['id'], 'verbose_name': 'MiembroEstado', 'verbose_name_plural': 'MiembroEstados'},
        ),
        migrations.AlterModelTable(
            name='miembrostatus',
            table='MiembroEstado',
        ),
    ]
