# Generated by Django 4.2.4 on 2024-01-09 05:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_miembro_phone_alter_miembro_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[app.models.validate_phone_prefix], verbose_name='TELEFONO'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='dni',
            field=models.BigIntegerField(blank=True, null=True, unique=True, validators=[app.models.validate_dni_length], verbose_name='CEDULA'),
        ),
    ]
