# Generated by Django 5.0.3 on 2024-05-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_miembro_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='dni',
            field=models.BigIntegerField(blank=True, max_length=10, null=True, unique=True, verbose_name='CEDULA'),
        ),
    ]
