# Generated by Django 5.0.2 on 2024-03-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_miembrostatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembrostatus',
            options={'verbose_name': 'StatusMiembro', 'verbose_name_plural': 'StatusMiembros'},
        ),
        migrations.AlterModelTable(
            name='miembrostatus',
            table=None,
        ),
    ]
