# Generated by Django 5.0.3 on 2024-06-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_miembro_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='CEDULA'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='TELEFONO'),
        ),
    ]
