# Generated by Django 4.2.4 on 2024-01-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_miembro_phone_alter_miembro_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='miembro',
            new_name='miembros',
        ),
    ]
