# Generated by Django 4.2.4 on 2024-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_miembro_attendance_miembros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='miembros',
        ),
        migrations.AddField(
            model_name='attendance',
            name='miembros',
            field=models.ManyToManyField(to='app.miembro'),
        ),
    ]
