# Generated by Django 4.2.4 on 2024-01-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_attendance_miembros_attendance_miembros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='miembros',
        ),
        migrations.AddField(
            model_name='attendance',
            name='miembros',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app.miembro', verbose_name='MIEMBROS'),
            preserve_default=False,
        ),
    ]
