# Generated by Django 4.2.4 on 2024-01-29 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_attendance_miembros_attendance_miembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='miembros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.miembro'),
        ),
    ]
