# Generated by Django 4.2.4 on 2024-02-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_attendance_miembros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='miembros',
            new_name='miembro',
        ),
    ]
