# Generated by Django 4.2.4 on 2024-02-18 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_miembros_attendance_miembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendance')),
            ],
            options={
                'verbose_name': 'Detalles',
                'verbose_name_plural': 'Detalles',
                'ordering': ['id'],
            },
        ),
    ]
